apiVersion: apps/v1
kind: Deployment
metadata:
  name: orakel-backend-mqtt-kolibri-receiver
  namespace:
spec:
  selector:
    matchLabels:
      app: orakel-backend-mqtt-kolibri-receiver
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: orakel-backend-mqtt-kolibri-receiver
        build: first-commit
    spec:
      imagePullSecrets:
        - name: orakel-gui-iamge-pull-secret
      containers:
        - image: registry.git-ce.rwth-aachen.de/wzl-mq-ms-rpc/code/research/predictive-quality/orakel-gui/orakel_backend:latest
          imagePullPolicy: Always
          name: main
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "0.5"
          command: ["python", "Mqtt/receiver.py"]
          env:
            - name: MQTT_RECEIVER_USERNAME
              value: ""
            - name: MQTT_RECEIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-receiver-password
                  key: key
            - name: MQTT_BROKER
              value: ""
            - name: MQTT_PORT
              value: "8883"
            - name: MQTT_VHOST
              value: ""
            - name: MQTT_KOLIBRI_TOPIC
              value: ""
            - name: MQTT_KOLIBRI_SUBTOPIC
              value: "sensorreadings"
            - name: CELERY_BROKER_URL
              value: "amqp://guest:guest@orakel-backend-api-rabbitmq:5672"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-secret-key
                  key: key
            - name: DEBUG
              value: "False"
            - name: HOST_DB
              value: "orakel-backend-mysql-default"
            - name: MEMCACHED
              value: "memcached-1:11211,memcached-2:11211"
            - name: MEMCACHED_BOOL
              value: "False"
            - name: ARGO_API_EXEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-api-token
                  key: token
            - name: superuser_username
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: username
            - name: superuser_password
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: password
            - name: superuser_email
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: email
            - name: mysql_user
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_user
            - name: mysql_password
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_password
            - name: mysql_database
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_database
