# Generated by Django 3.2 on 2021-04-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('machinetype', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, choices=[('Succeeded', 'Succeeded'), ('Running', 'Running'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Stopped', 'Stopped'), ('Other', 'Other'), ('Created', 'Created')], default='Other', max_length=100, null=True)),
                ('started', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended', models.DateTimeField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstep', to='orakel.machine')),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstep', to='orakel.operator')),
                ('preproduct', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstep', to='orakel.preproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realsensor', to='orakel.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool', to='orakel.machine')),
                ('processstep', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool', to='orakel.processstep')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('processstep', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.processstep')),
                ('realsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.realsensor')),
                ('virtualsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.virtualsensor')),
            ],
        ),
        migrations.AddField(
            model_name='realsensor',
            name='shopfloor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realsensor', to='orakel.shopfloor'),
        ),
        migrations.AddField(
            model_name='realsensor',
            name='tool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realsensor', to='orakel.tool'),
        ),
        migrations.CreateModel(
            name='QualityCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('targetvalue', models.FloatField(blank=True, default=None, null=True)),
                ('hardupperlimit', models.FloatField(blank=True, default=None, null=True)),
                ('hardlowerlimit', models.FloatField(blank=True, default=None, null=True)),
                ('softupperlimit', models.FloatField(blank=True, default=None, null=True)),
                ('softlowerlimit', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('productspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitycharacteristics', to='orakel.productspecification')),
                ('realsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitycharacteristics', to='orakel.realsensor')),
                ('virtualsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitycharacteristics', to='orakel.virtualsensor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('productspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='orakel.productspecification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessStepSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('optional', models.BooleanField(blank=True, default=None, null=True)),
                ('next_pss', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='orakel.processstepspecification')),
                ('previous_pss', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='orakel.processstepspecification')),
            ],
        ),
        migrations.AddField(
            model_name='processstep',
            name='processstepspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstep', to='orakel.processstepspecification'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstep', to='orakel.product'),
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('targetvalue', models.FloatField(blank=True, default=None, null=True)),
                ('hardupperlimit', models.FloatField(blank=True, default=None, null=True)),
                ('hardlowerlimit', models.FloatField(blank=True, default=None, null=True)),
                ('softupperlimit', models.FloatField(blank=True, default=None, null=True)),
                ('softlowerlimit', models.FloatField(blank=True, default=None, null=True)),
                ('unit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('processstepspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processparameter', to='orakel.processstepspecification')),
                ('realsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processparameter', to='orakel.realsensor')),
                ('virtualsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processparameter', to='orakel.virtualsensor')),
            ],
        ),
        migrations.AddField(
            model_name='preproduct',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preproduct', to='orakel.product'),
        ),
        migrations.AddField(
            model_name='preproduct',
            name='productspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preproduct', to='orakel.productspecification'),
        ),
        migrations.AddField(
            model_name='machine',
            name='shopfloor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='orakel.shopfloor'),
        ),
        migrations.CreateModel(
            name='InterProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('processstepspecification', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interproductspecification', to='orakel.processstepspecification')),
                ('productspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interproductspecification', to='orakel.productspecification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('interproductspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.interproductspecification')),
                ('machine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.machine')),
                ('operator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.operator')),
                ('preproduct', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.preproduct')),
                ('processparameter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.processparameter')),
                ('processstep', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.processstep')),
                ('processstepspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.processstepspecification')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.product')),
                ('productspecification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.productspecification')),
                ('qualitycharacteristics', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.qualitycharacteristics')),
                ('realsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.realsensor')),
                ('sensorreading', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.sensorreading')),
                ('shopfloor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.shopfloor')),
                ('tool', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.tool')),
                ('virtualsensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.virtualsensor')),
            ],
        ),
    ]
