# Generated by Django 3.1.5 on 2021-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstepspecification',
            name='next_pss',
        ),
        migrations.AddField(
            model_name='processstepspecification',
            name='next_pss',
            field=models.ManyToManyField(blank=True, default=None, related_name='next', to='orakel.ProcessStepSpecification'),
        ),
        migrations.RemoveField(
            model_name='processstepspecification',
            name='previous_pss',
        ),
        migrations.AddField(
            model_name='processstepspecification',
            name='previous_pss',
            field=models.ManyToManyField(blank=True, default=None, related_name='previous', to='orakel.ProcessStepSpecification'),
        ),
    ]
