# Generated by Django 3.1.5 on 2021-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0002_auto_20210421_1150'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processparameter',
            index=models.Index(fields=['processstepspecification'], name='orakel_proc_process_702da0_idx'),
        ),
        migrations.AddIndex(
            model_name='processparameter',
            index=models.Index(fields=['realsensor'], name='orakel_proc_realsen_3b0bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='processparameter',
            index=models.Index(fields=['virtualsensor'], name='orakel_proc_virtual_7bb35c_idx'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['product'], name='orakel_proc_product_132c46_idx'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['machine'], name='orakel_proc_machine_734e20_idx'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['processstepspecification'], name='orakel_proc_process_d6f82c_idx'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['preproduct'], name='orakel_proc_preprod_46b5da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['productspecification'], name='orakel_prod_product_4b083f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycharacteristics',
            index=models.Index(fields=['realsensor'], name='orakel_qual_realsen_293b57_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycharacteristics',
            index=models.Index(fields=['productspecification'], name='orakel_qual_product_abc1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycharacteristics',
            index=models.Index(fields=['virtualsensor'], name='orakel_qual_virtual_aeafca_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['realsensor', 'date'], name='orakel_sens_realsen_3a1db1_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['processstep'], name='orakel_sens_process_64588c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['virtualsensor'], name='orakel_sens_virtual_19f938_idx'),
        ),
    ]
