# Generated by Django 3.1.5 on 2021-05-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0003_auto_20210511_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='description',
        ),
    ]
