# Generated by Django 3.1.5 on 2021-05-27 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0004_auto_20210512_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Failed', 'Failed'), ('Succeeded', 'Succeeded'), ('Running', 'Running'), ('Other', 'Other')], default='Other', max_length=20)),
                ('save_path', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('max_rows', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('time_series_data', models.BooleanField(blank=True, default=False, null=True)),
                ('random_records', models.BooleanField(blank=True, default=True, null=True)),
                ('processstepspecification_choice', models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.int_list_validator])),
                ('processparameter_choice', models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.int_list_validator])),
                ('qualitycharacteristics_choice', models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.int_list_validator])),
                ('target_choice', models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.int_list_validator])),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineLearningRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Failed', 'Failed'), ('Succeeded', 'Succeeded'), ('Running', 'Running'), ('Other', 'Other')], default='Other', max_length=20)),
                ('save_path', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('parameter', models.JSONField(blank=True, default=None, null=True)),
                ('results', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineLearningRunSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('parameter', models.JSONField(blank=True, default=None, null=True)),
                ('pipeline_order', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('parameter', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]