# Generated by Django 3.1.5 on 2021-05-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0005_auto_20210527_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interproductspecification',
            name='processstepspecification',
        ),
        migrations.RemoveField(
            model_name='interproductspecification',
            name='productspecification',
        ),
        migrations.RemoveField(
            model_name='realsensor',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='realsensor',
            name='shopfloor',
        ),
        migrations.RemoveField(
            model_name='realsensor',
            name='tool',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='preproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='processparameter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='processstepspecification',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='qualitycharacteristics',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shopfloor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='interproductspecification',
        ),
        migrations.RemoveField(
            model_name='event',
            name='realsensor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='virtualsensor',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='realsensor',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='virtualsensor',
        ),
        migrations.RemoveField(
            model_name='qualitycharacteristics',
            name='productspecification',
        ),
        migrations.RemoveField(
            model_name='qualitycharacteristics',
            name='realsensor',
        ),
        migrations.RemoveField(
            model_name='qualitycharacteristics',
            name='virtualsensor',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='realsensor',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='virtualsensor',
        ),
        migrations.AddField(
            model_name='dataframe',
            name='processparameter',
            field=models.ManyToManyField(blank=True, default=None, related_name='dataframe', to='orakel.ProcessParameter'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='processstepspecification',
            field=models.ManyToManyField(blank=True, default=None, related_name='dataframe', to='orakel.ProcessStepSpecification'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='productspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataframe', to='orakel.productspecification'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='qualitycharacteristics',
            field=models.ManyToManyField(blank=True, default=None, related_name='dataframe', to='orakel.QualityCharacteristics'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='target_value',
            field=models.ManyToManyField(blank=True, default=None, related_name='target_value', to='orakel.QualityCharacteristics'),
        ),
        migrations.AddField(
            model_name='event',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='orakel.sensor'),
        ),
        migrations.AddField(
            model_name='machinelearningrun',
            name='machinelearningmodel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinelearningrun', to='orakel.machinelearningrunspecification'),
        ),
        migrations.AddField(
            model_name='machinelearningrunspecification',
            name='dataframe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinelearningrunspecification', to='orakel.dataframe'),
        ),
        migrations.AddField(
            model_name='pipelineblock',
            name='machinelearningrunspecification',
            field=models.ManyToManyField(blank=True, default=None, related_name='pipelineblock', to='orakel.MachineLearningRunSpecification'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processparameter', to='orakel.sensor'),
        ),
        migrations.AddField(
            model_name='qualitycharacteristics',
            name='processstepspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitycharacteristics', to='orakel.processstepspecification'),
        ),
        migrations.AddField(
            model_name='qualitycharacteristics',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitycharacteristics', to='orakel.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='machine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='orakel.machine'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='shopfloor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='orakel.shopfloor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='orakel.tool'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='processparameter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.processparameter'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='qualitycharacteristics',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.qualitycharacteristics'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorreading', to='orakel.sensor'),
        ),
        migrations.AddIndex(
            model_name='processparameter',
            index=models.Index(fields=['sensor'], name='orakel_proc_sensor__f2a5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycharacteristics',
            index=models.Index(fields=['sensor'], name='orakel_qual_sensor__4c8b64_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycharacteristics',
            index=models.Index(fields=['processstepspecification'], name='orakel_qual_process_4cbd11_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['processparameter'], name='orakel_sens_process_4d42a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['qualitycharacteristics'], name='orakel_sens_quality_f5f55a_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor'], name='orakel_sens_sensor__6077ef_idx'),
        ),
        migrations.DeleteModel(
            name='InterProductSpecification',
        ),
        migrations.DeleteModel(
            name='RealSensor',
        ),
        migrations.DeleteModel(
            name='VirtualSensor',
        ),
    ]
