# Generated by Django 3.1.5 on 2021-05-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0006_auto_20210531_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='machinelearningrun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='orakel.machinelearningrun'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='virtual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='qualitycharacteristics',
            name='sensor',
        ),
        migrations.AddField(
            model_name='qualitycharacteristics',
            name='sensor',
            field=models.ManyToManyField(blank=True, default=None, related_name='next', to='orakel.Sensor'),
        ),
    ]
