# Generated by Django 3.1.5 on 2021-05-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0007_auto_20210531_1713'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processparameter',
            name='orakel_proc_realsen_3b0bb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='processparameter',
            name='orakel_proc_virtual_7bb35c_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitycharacteristics',
            name='orakel_qual_realsen_293b57_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitycharacteristics',
            name='orakel_qual_product_abc1bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitycharacteristics',
            name='orakel_qual_virtual_aeafca_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitycharacteristics',
            name='orakel_qual_sensor__4c8b64_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='orakel_sens_realsen_3a1db1_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='orakel_sens_virtual_19f938_idx',
        ),
    ]
