# Generated by Django 3.1.5 on 2021-06-01 18:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0008_auto_20210531_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframe',
            name='target_choice',
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='processparameter_choice',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=None, null=True, size=10000),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='processstepspecification_choice',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=None, null=True, size=100),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='qualitycharacteristics_choice',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=None, null=True, size=10000),
        ),
    ]
