# Generated by Django 3.1.5 on 2021-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0009_auto_20210601_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningrun',
            name='argo_job_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machinelearningrunspecification',
            name='argo_template',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pipelineblock',
            name='argo_template',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
