# Generated by Django 3.1.5 on 2021-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0010_auto_20210615_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineblock',
            name='argo_template',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
