# Generated by Django 3.2 on 2021-07-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0011_auto_20210623_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstepspecification',
            name='productspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstepspecification', to='orakel.productspecification'),
        ),
    ]
