# Generated by Django 3.2 on 2021-07-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0011_auto_20210623_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineBlockSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('parameter', models.JSONField(blank=True, default=None, null=True)),
                ('argo_template', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('argo_template_entrypoint', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pipelineblock',
            name='argo_template',
        ),
        migrations.AddField(
            model_name='pipelineblock',
            name='pipelineblockspecification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelineblock', to='orakel.pipelineblockspecification'),
        ),
    ]
