# Generated by Django 3.2 on 2021-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0011_auto_20210623_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='name',
        ),
    ]
