# Generated by Django 3.2 on 2021-07-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0012_processstepspecification_productspecification'),
        ('orakel', '0012_remove_sensorreading_name'),
    ]

    operations = [
    ]
