# Generated by Django 3.2 on 2021-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0012_auto_20210713_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinelearningrunspecification',
            name='parameter',
        ),
        migrations.AddField(
            model_name='machinelearningrunspecification',
            name='create_new_template',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
