# Generated by Django 3.2 on 2021-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0014_merge_20210716_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningrunspecification',
            name='create_new_template',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
