# Generated by Django 3.2 on 2021-07-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0015_alter_machinelearningrunspecification_create_new_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningrunspecification',
            name='save_path',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningrunspecification',
            name='argo_template',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
