# Generated by Django 3.2 on 2021-07-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0016_auto_20210719_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinelearningrun',
            old_name='machinelearningmodel',
            new_name='machinelearningrunspecification',
        ),
    ]
