# Generated by Django 3.2 on 2021-07-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0013_merge_20210719_0804'),
        ('orakel', '0017_rename_machinelearningmodel_machinelearningrun_machinelearningrunspecification'),
    ]

    operations = [
    ]
