# Generated by Django 3.2 on 2021-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0018_merge_20210722_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycharacteristics',
            name='sensor',
            field=models.ManyToManyField(blank=True, default=None, related_name='qualitycharacteristics', to='orakel.Sensor'),
        ),
    ]
