# Generated by Django 3.2 on 2021-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0020_auto_20210727_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='max_rows',
            field=models.PositiveIntegerField(default=500000),
        ),
    ]
