# Generated by Django 3.2 on 2021-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0022_auto_20210728_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningrun',
            name='deployed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
