# Generated by Django 3.2 on 2021-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0023_machinelearningrun_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningrun',
            name='inference',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
