# Generated by Django 3.2 on 2021-09-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orakel', '0024_machinelearningrun_inference'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstepspecification',
            name='machinelearningrun',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processstepspecification', to='orakel.machinelearningrun'),
        ),
    ]
