apiVersion: v1
kind: Service
metadata:
  name: orakel-backend-mysql-default
  namespace:
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-default
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orakel-backend-mysql-default
  namespace: 
spec:
  selector:
    matchLabels:
      app: mysql-default
  replicas: 1
  minReadySeconds: 120
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-default
    spec:
      containers:
        - image: mysql:8.0.23
          name: mysql
          resources:
            requests:
              memory: "3Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_database
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: orakel-backend-mysql-storage
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: orakel-backend-mysql-storage
          persistentVolumeClaim:
            claimName: orakel-backend-mysql-pvc-default
        - name: mysql-config-volume
          configMap:
            name: backend-mysql-config
