apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-mysql-config
  namespace: 
  labels:
    app: backend-mysql
data:
  my.cnf: |
    [mysqld]
      default_authentication_plugin = mysql_native_password
      explicit_defaults_for_timestamp = 1
      innodb_flush_method=O_DIRECT
      innodb_buffer_pool_size=2.4G
      innodb_log_buffer_size=8M
      innodb_thread_concurrency=4
      disable_log_bin
