apiVersion: apps/v1
kind: Deployment
metadata:
  name: orakel-backend-api
  namespace:
spec:
  selector:
    matchLabels:
      app: orakel-backend-api
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: orakel-backend-api
        build: first-commit
    spec:
      imagePullSecrets:
        - name: orakel-gui-iamge-pull-secret
      volumes:
        - name: keycloak-vol
          secret:
            secretName: keycloak-config
      containers:
        - image: registry.git-ce.rwth-aachen.de/wzl-mq-ms-rpc/code/research/predictive-quality/orakel-gui/orakel_backend:latest
          imagePullPolicy: Always
          name: orakel-backend-api-main
          volumeMounts:
            - name: keycloak-vol
              mountPath: "/code/keycloak.json"
              subPath: "keycloak.json"
          ports:
            - containerPort: 8000
              name: django-web
              protocol: TCP
          resources:
            requests:
              memory: "3Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
          env:
            - name: CELERY_BROKER_URL
              value: "orakel-backend-api-rabbitmq"
            - name: DEBUG
              value: "False"
            - name: HOST_DB
              value: "orakel-backend-mysql-default"
            - name: MEMCACHED
              value: "memcached-1:11211,memcached-2:11211"
            - name: MEMCACHED_BOOL
              value: "False"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-secret-key
                  key: key
            - name: ARGO_API_EXEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argo-api-token
                  key: token
            - name: superuser_username
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: username
            - name: superuser_password
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: password
            - name: superuser_email
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: email
            - name: mysql_user
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_user
            - name: mysql_password
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_password
            - name: mysql_database
              valueFrom:
                secretKeyRef:
                  name: orakel-backend-mysql-secret
                  key: mysql_database
