apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orakel-backend-mysql-pvc-default
  namespace: 
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
